CREATE TABLE Customer ( 
CustomerId VARCHAR(10) PRIMARY KEY,
CustomerName VARCHAR(50) NOT NULL,  
Phone VARCHAR(10) NOT NULL,  
Address VARCHAR(50) NOT NULL,
DOB VARCHAR(15) NOT NULL, 
InsertedTime DATETIME DEFAULT CURRENT_TIMESTAMP 
);  
